server_address: "192.168.185.25:50059"
mir_address: "192.168.12.20"
robot_name: "ChargePal1"
robot_id: 'ER-FLEX-00040'
sim_flag: True
recovery_enabled: False
battery_communication: False
server_timeout: 600 #seconds (10 minutes)
rdb_path: "chargepal_bundle/db/rdb.db"
rdbc_path: "chargepal_bundle/db/rdb_copy.db"
log_file_path: "chargepal_bundle/logs/chargepal_logs.txt"
arrive_at_station_enabled: True
pickup_cart_enabled: True
drop_cart_enabled: True
plugin_enabled: True
plugout_enabled: True
